require 'rake_tasks'

#################################

controller_tasks = [
  'checks::support',
  'checks::settings',
  'network::nova',
  'network::hosts',
  'mysql::simple',
  'keystone::db::mysql',
  'keystone::install',
  'keystone::admin_role',
  'keystone::endpoint',
  'rabbitmq::install',
  'rabbitmq::users',
  'cinder::db::mysql',
  'cinder::base',
  'cinder::volume::iscsi',
  'cinder::api',
  'cinder::scheduler',
  'nova::db::mysql',
  'nova::keystone::auth',
  'nova::common',
  'nova::api',
  'nova::cert',
  'nova::conductor',
  'nova::consoleauth',
  'nova::objectstore',
  'nova::scheduler',
  'nova::vncproxy',
  'memcached',
  'horizon',
  'openstack::auth_file',
]

demo_tasks = [
  'demo::apache::install',
  'demo::apache::start',
  'demo::hello_world_page',
]

################################

deploy_preset 'controller', controller_tasks, 'Deployment of the Simple Controller'
deploy_preset 'demo', demo_tasks, 'A set of demo tasks that deploy apache'
