require 'rake_tasks'

#################################

empty_tasks = [
  'test:empty1',
  'test:empty2',
  'test:empty3',
]

example_tasks = [
  'example',
]

################################

deploy 'empty', empty_tasks
deploy 'examples', example_tasks
